### ISSUE TITLE
False possitive when class is used in parent / child

### ISSUE THREAD

**Issue by andyhot** [soundasleep/emberjs-handlebars-sanity#2]
I get incorrect results when running the checker on templates such as:

`<div class="no"><i {{bind-attr class=icon_class}}></i></div>`

The error reported is

> Found template with duplicate attribute and attribute binding 'class' in app/templates/components/map-creator.hbs.
> This will mean one of the attributes will be silently ignored.
> Try using e.g. {{bind-attr class=":static dynamic}}.

**Comment by soundasleep** [comment]
This has been fixed in PR #3, thank you!
